### ISSUE TITLE
origami-close-node collapses entire hierarchy

### ISSUE THREAD

**Issue by jvburnes** [gregsexton/origami.el#16]
When I execute origami-close-node on a child node it collapses the node from the topmost parent node, not from the current node.  Is this what origami is supposed to do?  From reading the docs origami definitely supports child nodes and multi-level folding.  (if it didn't it would be of extremely limited us).

**Comment by gregsexton** [comment]
This is not the correct behaviour. `origami-close-node` should just close the current node - it won't even close children, they'll just be hidden. Is this still an issue for you? Can you provide a sample and some steps so that I can reproduce?

**Comment by gregsexton** [comment]
Haven't heard from you in a while. Feel free to comment if this is still an issue.
