### ISSUE TITLE
make origami-hide-node-overlay more light and more

### ISSUE THREAD

**Issue by c02y** [gregsexton/origami.el#2]
In origami.el, you make the face of overlay(...)  `font-lock-comment-delimiter-face`, which is grey in my theme, which is not so easy to notice. I think a more light color like red or yellow would be better.

Check the image at [yafolding](https://github.com/zenozeng/yafolding.el), it shows arrow fringe marks at the left fringe of the window to make the fold block more noticeable, you should do that too. Check https://github.com/zenozeng/yafolding.el/blob/master/yafolding.el#L48-L52 for code.

**Comment by gregsexton** [comment]
This is now configurable. See origami-fold-replacement-face
