### ISSUE TITLE
Add python support

### ISSUE THREAD

**Issue by bbenne10** [gregsexton/origami.el#22]
[Here](https://github.com/gregsexton/origami.el/blob/master/origami-parsers.el#L220) python-mode is bound to `origami-indent-parser`. This is convienent in the simple case, but there are a number of instances where this is less than useful. For example:

```python
@route('/')
def render_root():
    return "asdf"
```

The above will fold to

```python
@route('/')...
```

This is frustrating because you can no longer see the name of the function being decorated. I intend to see if there's a way to fix this simply, but my elisp-fu is weak. Wanted to open to have a discussion about a possible fix.

**Comment by gregsexton** [comment]
I hear you. Yeah indentation-based folding kinda sucks. It was added as a possibly useful fallback for when 'real' support isn't available. The complete fix is to write a python parser. You may be able to come up with some heuristics though that give you more preferable behaviour. Possibly defining blocks as: all following lines with greater indentation after a line ending in a colon. This should cover definitions, loops, conditionals etc.

**Comment by bbenne10** [comment]
It strikes me that the one problem I've run into so far is that when collapsing a block, the topmost line of the same indentation level is the one shown (as described above). Nothing else seems bound to the 
indent parser explicitly, so changing this behavior shouldn't affect too many other languages (but might be inconvenient for some). If you've no objection, I may stumble around in the code a bit to see
if I can "fix" this behavior and open a pull request if I should miraculously get something working.

**Comment by gregsexton** [comment]
I'm not sure I understand what change you're proposing. When collapsing a block based on indent, what else would you show other than the top line? Just fyi: the indent parser is the default if nothing else is defined so changing it might actually have a wide impact. Feel free to send a PR but I would probably be more comfortable with you forking the indent parser if you're making changes that are domain specific.

**Comment by humitos** [comment]
I review the parsers code and I was unable to understand how to create a new parser :(

I would like to create something simple for Python. I don't want to fold conditionals or loops, just `def` and `class` which are the most common annoying cases for me.

With `(origami-get-positions (buffer-string) "def\\|class")` I can get all the `def` and `class` positions, but I don't which function could help me to make the folding at the next `def|class`. I mean, from one of the positions in that list, fold to the next one.

I think that for me it's a good start and a simple approach but I don't have the elisp knowledge to build it by myself.

**Comment by gregsexton** [comment]
Your lucky day. I had to work with some python code recently so hacked up some support. This folds all top level functions and classes. Was good enough for me...
