### ISSUE TITLE
Collapsing top-level lines leads to issues

### ISSUE THREAD

**Issue by bbenne10** [gregsexton/origami.el#23]
Sorry for opening two issues in as many minutes!

When folding code based with the indentation parser, the outer indentation level is collapses as well. An example:

```python
class Foo(object):
    """A docstring!"""
    def __init__(self, foo, bar):
        self.foo = foo
        self.bar = bar
```

With the cursor over the `def __init__(...)` line,  I would expect the `__init__`  method definition to be closed and the `def __init__(...)` line to become `def __init__(...):...`. What I receive, however, is 

```python
class Foo(object):
    """A docstring!"""...
```

Is my expectation incorrect here? Or is there a possibility for improvement?

**Comment by gregsexton** [comment]
I'm afraid this doesn't work as you expect. Origami collapses everything of that indentation level. To get the behaviour you're expecting you should collapse on one of the `self.xxx = xxx` lines.
