### ISSUE TITLE
Support for C-Makros

### ISSUE THREAD

**Issue by forflo** [gregsexton/origami.el#27]
It'd be very nice if annoying makros like

```
    #ifdef FOO
    printf("annoying poor man's debug\n");
    #endif
```

could be transformed into something like

```
     #ifdef FOO {...}
```

If you don't have the time, let me know. I'll try to write it on my own then...

**Comment by gregsexton** [comment]
This would be cool. I'll certainly add it to the backlog but if you want to have a go please feel free to send a PR. :)
