### ISSUE TITLE
Auto folding when opening a file (as a mode hook)

### ISSUE THREAD

**Issue by bu2** [gregsexton/origami.el#32]
Hi,

Thanks for that great plugin for Emacs.

I am trying to set my emacs config to run origami-close-all-nodes when opening C/C++ files.
Could you advise on the right config snippet to paste in my init.el ?

For the moment, I tried things like that (see the last 2 add-hooks) :

```
;; Configure origami
(require 'origami)
(add-hook 'c-mode-common-hook
          (lambda ()
            (when (derived-mode-p 'c-mode 'c++-mode 'java-mode 'asm-mode)
              (origami-mode 1))))
(add-hook 'c-mode-hook 'origami-close-all-nodes)
(add-hook 'c++-mode-hook 'origami-close-all-nodes)
(define-key origami-mode-map (kbd "C-z o") 'origami-open-node)
(define-key origami-mode-map (kbd "C-z c") 'origami-close-node)
(define-key origami-mode-map (kbd "C-z k") 'origami-close-all-nodes)
```

But it does not work as expected : it does nothing except giving the following error :
`File mode specification error: (wrong-number-of-arguments (1 . 1) 0)
`

Regards.

**Comment by gregsexton** [comment]
You need two things: origami to be enabled and to call the functions interactively. They're designed to be callable programatically and so unless they're called interactively you need to pass them args. That's why you get the wrong number of args error.

Below works for me:

```
(add-hook 'c++-mode-hook (lambda () (interactive)
                                  (origami-mode 1)
                                  (call-interactively 'origami-close-all-nodes)) t)
```
