### ISSUE TITLE
Folding a node with a comment directly above it

### ISSUE THREAD

**Issue by therockmandolinist** [gregsexton/origami.el#33]
In `python.el`, if there is a comment directly above a function, for loop, etc., I'm getting text folded into the comment line, rather than into the `def`,`for`,`if`, etc.

**Comment by gregsexton** [comment]
This is expected behaviour. There isn't a python-specifc parser so we just use indentation as a guide. origami is unable to tell the difference between a comment and a function. 

See #22

**Comment by indigoviolet** [comment]
Any chance we can fix this for ruby as well?

**Comment by gregsexton** [comment]
See #11
