### ISSUE TITLE
How to add custom folding

### ISSUE THREAD

**Issue by arkhan** [gregsexton/origami.el#47]
Hello, 

How to folding block comments, like: 

---{{{ ---}}} for lua. 

Thank's

**Comment by paullemmens** [comment]
I'm also struggling to get custom folding to work properly. In my R markdown files, code chunks are contained with

    ```{r chunk-name}
    ## R code
    ```

I think I could use the `(origami-markers-parser)` but that gives errors when I use the function in my spacemacs(!) configuration using `  (add-to-list 'origami-parser-alist (poly-markdown+r-mode . (origami-markers-parser "```{r" "```")))`. The error is that `origami-markers-parser` is void; when I add the `,` like in the example file, the comma is evaluated to void.

**Comment by arkhan** [comment]
Thanks

**Comment by paullemmens** [comment]
Hi @arkhan, not sure why you closed the issue? Could you explain your solution to me too, if you found one?

**Comment by ztlevi** [comment]
All you have to do is adding a ` before the parentheses.
```
  (add-to-list 'origami-parser-alist `(ruby-mode . (origami-markers-parser "```{r " "```")))
```

**Comment by paultopia** [comment]
Just in case future people trying to use custom parsers happen upon this old issue--- ztlevi's suggestion seems to get the quoting wrong.  You actually need to backquote the sexp starting with the node name, and then unquote the sexp starting with `origami-markers-parser`.  For example (my code that works):

```
(add-to-list 'origami-parser-alist `(markdown-mode . ,(origami-markers-parser "{" "}")))
```

Honestly, I'm not good enough the intricacies of macros and quoting to know why this is the case, but I just spent like 45 minutes trying chunk of code after chunk of code after chunk of code to try to get a custom fold to work in markdown, and getting useless "invalid function" errors over and over, but that technique is the only thing that got it to work.
