### ISSUE TITLE
Is there anyway to unfold current fold using tab?

### ISSUE THREAD

**Issue by adamcavendish** [gregsexton/origami.el#54]
For example, I have a cursor at `|{ ...}` or `{...}|`, and I press tab here. It automatically unfold this fold  by calling `origami-open-node`.

**Comment by gregsexton** [comment]
You can bind the tab key to origami-open-node. Is this not working for you?

Off the top of my head, something like `(global-set-key (kbd "TAB") 'origami-recursively-toggle-node)` is probably what you want. It uses heuristics to jump to a fold by searching forward and will expand the entry further as you keep pressing tab.

**Comment by adamcavendish** [comment]
Yeah, but if the "TAB" key has already been assigned (yasnippet), how can we chain the actions?

**Comment by anachronic** [comment]
I'm sorry to meddle but I think I have a solution.

It turns out yasnippet only remaps the key when it's looking at a snippet pattern. This might be different in previous versions. I really don't know.

All you really have to do is remap the function mapped to tab key when its **not** looking at a snippet. In my case that is `indent-for-tab-command`. You can use what origami provides like so:

```
(defun origami-closed-here-p ()
    (let* ((path (origami-search-forward-for-path (current-buffer) (point)))
           (node (-last-item path)))
      (origami-fold-node-recursively-closed? node)))

  (defun origami-expand-or-TAB (&optional ARG)
    (interactive)
    (if (origami-closed-here-p)
        (origami-show-node (current-buffer) (point))
      (call-interactively 'indent-for-tab-command)))

  (global-set-key [remap indent-for-tab-command] 'origami-expand-or-TAB)
```

**Comment by aaronjensen** [comment]
Thanks @anachronic! Here's mine I've adapted slightly to make it toggle and only work for `{{{`:

```
  (defun aj/origami-toggle-or-TAB (&optional arg)
    "Toggle current fold or use regular tab."
    (interactive)
    (if (and (local-variable-p 'origami-fold-style)
             (eq origami-fold-style 'triple-braces)
             (save-excursion
               (beginning-of-line)
               (or (looking-at-p (concat ".*}}" "}"))
                  (looking-at-p (concat ".*{{" "{")))))
        (progn
          (beginning-of-line)
          (origami-forward-toggle-node (current-buffer) (point)))
      (call-interactively 'indent-for-tab-command)))

  (global-set-key [remap indent-for-tab-command] 'aj/origami-toggle-or-TAB)
```
