### ISSUE TITLE
really like this mode, wish it could support reStructuredText :)

### ISSUE THREAD

**Issue by xieyuheng** [gregsexton/origami.el#58]

**Comment by xieyuheng** [comment]
by the way,
your current github avatar might be generated by github, 
but in Chinese, 火 means fire. 
:: http://ctext.org/dictionary.pl?if=en&char=%E7%81%AB

**Comment by wbolster** [comment]
https://github.com/gregsexton/origami.el/issues/69 may be of interest to you :)

**Comment by wbolster** [comment]
![image](https://user-images.githubusercontent.com/748944/38734485-28e50a16-3f26-11e8-9de7-dcf59bd8270e.png)

**Comment by xieyuheng** [comment]
thx @wbolster :)
I was thinking about replacing some of my usages of org-mode by rst, when making this issues.
I read #69, and tried your parser.
but it did not work for me.

maybe the problem is about imenu,
I saw the function `imenu--make-index-alist`
but I do not have this function.

also, I do not know about the macro `-as->`
it seems like a threading macro, but more than `->`.
where could I learn more about it ?

**Comment by wbolster** [comment]
the `-as->` threading macro is from `dash.el`.

coincidentally, a melpa stable version containing `-as->` was released a few hours ago:
https://github.com/magnars/dash.el/issues/243

**Comment by wbolster** [comment]
`imenu--make-index-alist` is an internal function from `imenu` which is included emacs. try `(require 'imenu)` to force it to be loaded.
