### ISSUE TITLE
FEATURE: Global Origami Mode

### ISSUE THREAD

**Issue by LeoAdamek** [gregsexton/origami.el#7]
It'd be great to have a `global-origami-mode` minor mode, so that we don't have to explicitly `add-hook` for each mode we want `origami-mode` we want origami features available on.

Suggest that `global-origami-mode` would simply enable `origami-mode` for any mode which has a parser set in `origami-parser-alist`

Just a suggestion having just started using origami mode, so I don't know if this already exists.

Works fantastically with Go and PHP using the `origami-c-style-parser` :bangbang: 

## EDIT:

It is possible to emulate this behavior by using the following snippet and provided by yafolding:

```elisp
(add-hook 'prog-mode-hook
   (lambda () (origami-mode)))
```

-Leo

**Comment by gregsexton** [comment]
Sorry this took me so long to get to. I've added the global mode and also added go and php to the default parsers alist.
