### ISSUE TITLE
How to add left visual clue

### ISSUE THREAD

**Issue by priyadarshan** [gregsexton/origami.el#8]
Thank you for `origami`, I like it very much. One thing I miss from other similar solutions is a visual cue on the *left* of the fold (beside the ellipses on the right), similar, for example, to `yafolding` (see [image here](https://camo.githubusercontent.com/452fa678957f5d69b6a41aafb081b101b59eaf53/68747470733a2f2f7261772e6769746875622e636f6d2f7a656e6f7a656e672f7961666f6c64696e672e656c2f6d61737465722f7073632e706e67)). I find a left visual clue helps my productivity quite a bit more.

 Is there any setting one could use to customise the visual clues, both left and right of the folding?

Thanks once again!

**Comment by Trevoke** [comment]
I would also like this feature.

**Comment by seckar** [comment]
[This branch](https://github.com/seckar/origami.el/tree/customize-display) highlights the line folding starts on, and adds an indicator in the fringe. The indicator is not customizable, but could be made so. Highlighting can be effectively turned off (while leaving the fringe indicator on) via customization if desired. The result looks like this:

<img width="719" alt="origami2" src="https://cloud.githubusercontent.com/assets/41155/10418774/a81733f6-7019-11e5-8904-5cc5e0165f26.png">

**Comment by stardiviner** [comment]
I like this style. Great.

**Comment by gregsexton** [comment]
Looks great. Submit a pull request and I'll see what I can merge. Thanks.

**Comment by stardiviner** [comment]
@seckar Do you want to send a push request? I'm expecting for your new feature.

**Comment by stardiviner** [comment]
Is this feature merged?

**Comment by vsrepo** [comment]
Last commit is from Aug 22, 2015, so I do no think there is any progress on this. I am also looking forward to it.

**Comment by gregsexton** [comment]
Sorry. Life has been crazy busy for me recently. I have a backlog of issues and prs that I will be trying to clear. I have every intention of merging this.

**Comment by stardiviner** [comment]
Thank you for take time to merge.

**Comment by gregsexton** [comment]
Merged #18 . Please pull the latest code and be sure to `(setq origami-show-fold-header t)`.
