### ISSUE TITLE
package.el link

### ISSUE THREAD

**Issue by andschwa** [gregsexton/origami.el#9]
Hi,

The homepage link for the package (when viewed in `M-x list-packages` goes to your [user](https://github.com/gregsexton) and not the [repo](https://github.com/gregsexton/origami.el), which meant to find it I had to hunt.

Just FYI.

Cheers,

Andy

P.S. I love this package.

**Comment by gregsexton** [comment]
Thanks for fixing this! Glad you like the package. :)

**Comment by andschwa** [comment]
My wife has been looking for code folding for Emacs, I was so glad to share this with her. Thanks for developing it @gregsexton!
